### ISSUE TITLE
IOException: Too many open files

### ISSUE THREAD

**Issue by stevendobay** [stevendobay/wex#3]
[error] (Thread-1) java.io.IOException: Too many open files
java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        at wex.Server.wex$Server$$handleKey(Server.scala:72)
        at wex.Server$$anon$1.run(Server.scala:63)

**Comment by stevendobay** [comment]
Problem with|mechanics of the unix system - there is a limit for open file descriptors(against fork bombs) and the server can't close the files as fast as the tests connect. _Increasing_ the open files limit solves the problem:

add "fs.file-max 1000000" to **/etc/sysctl.conf** then run sysctl -p
add

```shell

* soft nofile 40960
* hard nofile 1024000
```

to **/etc/security/limits.conf**, the '*' means for all users and can be replaced by a username.** Restart the machine.**  With _/proc/sys/fs/file-nr_ one could check the allocated/available/max file handles.
